---

- name: Installing Debian family dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
      - build-essential
      - zlib1g-dev
      - libextutils-cbuilder-perl
      - libmodule-install-perl
      - gettext
      - asciidoc 
      - xmlto 
      - wget
      - unzip
      - make
      - autoconf
      - gcc 
 
